# Generated by Django 5.2.6 on 2025-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='description',
        ),
        migrations.AddField(
            model_name='drink',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='dificuldade',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='drink',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='drinks/'),
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredientes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
